version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.8.4
    env_file:
      - .env
    environment:
      _PIP_ADDITIONAL_REQUIREMENTS: -r /requirements.txt
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - .:/opt/airflow/nba_project
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.4
    env_file:
      - .env
    environment:
      _PIP_ADDITIONAL_REQUIREMENTS: -r /requirements.txt
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - .:/opt/airflow/nba_project
      - ./requirements.txt:/requirements.txt
    command: scheduler

volumes:
  postgres-db-volume:
